= Fuzzy-CSV
:toc: left
:source-highlighter: coderay
:toclevels: 4
FuzzyCSV is a lightweigt groovy data processing library that helps in shaping and cleaning your dataset before its consumed by another service.

== GET FuzzyCsv

FuzzyCsv is published to both maven central and jitpack.io.
Starting from 1.7.1 all versions of FuzzyCSV will be published to maven central

=== GET FUZZYCSV FROM MAVEN CENTRAL

For maven add the dependency to your pom file like this

Maven

[source,xml]
----
<dependency>
     <groupId>io.github.kayr</groupId>
     <artifactId>fuzzy-csv</artifactId>
     <version>${version}</version>
</dependency>
----

Gradle:

[source,groovy]
----
 compile 'io.github.kayr:fuzzy-csv:${version}'
----

=== GET FUZZYCSV FROM JITPACK.IO

The to get artefacts from jipack the name space changes from `io.github.kayr` to `com.github.kayr`.

For Maven

[source,xml]
-----

    ...
    <!-- Add this Repository -->
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    ...
    <dependency>
            <groupId>com.github.kayr</groupId>
            <artifactId>fuzzy-csv</artifactId>
            <version>${version}</version>
    </dependency>
    ...
-----

For Gradle

[source,groovy]
-----
repositories {
    /* Add this repository */
    maven { url 'https://jitpack.io' }
}

dependencies{
    ...
    compile 'com.github.kayr:fuzzy-csv:${version}'
    ...
}
-----

== USAGE

=== DATA INITIALIZATION

==== Loading Data into Fuzzy-CSV

[source,groovy]
----
include::samples/loading.groovy[tag=code]
----

==== Visualize json data in a console grid table

You can convert json text to a grid console table.

[source,groovy]
----
include::samples/gridify.groovy[tag=code]
----
_Output_
....
╔═════════╤═══════════════════════════════════════════╗
║ key     │ value                                     ║
╠═════════╪═══════════════════════════════════════════╣
║ id      │ 0001                                      ║
╟─────────┼───────────────────────────────────────────╢
║ type    │ donut                                     ║
╟─────────┼───────────────────────────────────────────╢
║ name    │ Cake                                      ║
╟─────────┼───────────────────────────────────────────╢
║ ppu     │ 0.55                                      ║
╟─────────┼───────────────────────────────────────────╢
║ batters │ ╔════════╤══════════════════════════════╗ ║
║         │ ║ key    │ value                        ║ ║
║         │ ╠════════╪══════════════════════════════╣ ║
║         │ ║ batter │ ╔══════╤═══════════╤═══════╗ ║ ║
║         │ ║        │ ║ id   │ type      │ color ║ ║ ║
║         │ ║        │ ╠══════╪═══════════╪═══════╣ ║ ║
║         │ ║        │ ║ 1001 │ Regular   │ -     ║ ║ ║
║         │ ║        │ ╟──────┼───────────┼───────╢ ║ ║
║         │ ║        │ ║ 1002 │ Chocolate │ Brown ║ ║ ║
║         │ ║        │ ╚══════╧═══════════╧═══════╝ ║ ║
║         │ ╚════════╧══════════════════════════════╝ ║
╟─────────┼───────────────────────────────────────────╢
║ topping │ ╔══════╤════════╤═══════╗                 ║
║         │ ║ id   │ type   │ color ║                 ║
║         │ ╠══════╪════════╪═══════╣                 ║
║         │ ║ 5001 │ None   │ -     ║                 ║
║         │ ╟──────┼────────┼───────╢                 ║
║         │ ║ 5002 │ Glazed │ -     ║                 ║
║         │ ╟──────┼────────┼───────╢                 ║
║         │ ║ 5005 │ Sugar  │ Brown ║                 ║
║         │ ╚══════╧════════╧═══════╝                 ║
╚═════════╧═══════════════════════════════════════════╝

....


=== RECORD FUNCTIONS

These Help you write expression or functions for a record.E.g A function multiplying price by quantity.The record function run in two modes:

- One with type coercion which can be created using `RecordFx.fn{}`.This mode is lenient and does not throw most exceptions.This mode supports division of nulls(`null/2`), zero(`2/0`) division and type coercion(`"2"/2 or Object/null`) . This mode adds extra overhead and is much slower if your are dealing with lots of records.
- Another mode is `RecordFx.fx{}` which uses the default groovy evaluator.This mode is much faster if you are working with lots of records.However, this mode is not lenient and hence can throw `java.lang.ArithmeticException: Division by zero`.If you want to enable leniency but still want to use the faster `RecordFx.fx{}` you can wrap your code in the `fuzzycsv.FxExtensions` category(e.g `use(FxExtensions){ ...code here.. }`) So the category is registered only once as compared to the former where the category is reqistered on each and every evaluation.

=== DATA MERGING

==== Merging with a fuzzy match

1. Set the accuracy threshold to 75%
2. Merge using code below

[source,groovy]
----
include::samples/merging.groovy[tag=code]
----
_Output_
....
╔════════════╤════════╤═════╗
║ first name │ sex    │ age ║
╠════════════╪════════╪═════╣
║ alex       │ male   │ -   ║
╟────────────┼────────┼─────╢
║ sara       │ female │ -   ║
╟────────────┼────────┼─────╢
║ alex       │ male   │ 21  ║
╟────────────┼────────┼─────╢
║ peter      │ male   │ 21  ║
╚════════════╧════════╧═════╝

....

Notice how it merged *[first name]* and *[ferts nama]*

==== Joins

===== Inner join

[source,groovy]
----
include::samples/join-inner.groovy[tag=code]
----
_Output_
....
╔══════╤══════╤═════╤════════╗
║ name │ sex  │ age │ hobby  ║
╠══════╪══════╪═════╪════════╣
║ alex │ male │ 21  │ biking ║
╚══════╧══════╧═════╧════════╝

....


===== Left Join

[source,groovy]
----
include::samples/join-left.groovy[tag=code]
----
_Output_
....
╔══════╤════════╤═════╤════════╗
║ name │ sex    │ age │ hobby  ║
╠══════╪════════╪═════╪════════╣
║ alex │ male   │ 21  │ biking ║
╟──────┼────────┼─────┼────────╢
║ sara │ female │ -   │ -      ║
╚══════╧════════╧═════╧════════╝

....


===== Right Join

[source,groovy]
----
include::samples/join-right.groovy[tag=code]
----
_Output_
....
╔═══════╤══════╤═════╤══════════╗
║ name  │ sex  │ age │ hobby    ║
╠═══════╪══════╪═════╪══════════╣
║ alex  │ male │ 21  │ biking   ║
╟───────┼──────┼─────┼──────────╢
║ peter │ -    │ 21  │ swimming ║
╚═══════╧══════╧═════╧══════════╝

....


===== Full Join

[source,groovy]
----
include::samples/join-full.groovy[tag=code]
----
_Output_
....
╔═══════╤════════╤═════╤══════════╗
║ name  │ sex    │ age │ hobby    ║
╠═══════╪════════╪═════╪══════════╣
║ alex  │ male   │ 21  │ biking   ║
╟───────┼────────┼─────┼──────────╢
║ sara  │ female │ -   │ -        ║
╟───────┼────────┼─────┼──────────╢
║ peter │ -      │ 21  │ swimming ║
╚═══════╧════════╧═════╧══════════╝

....


===== Join With Custom Function

[source,groovy]
----
include::samples/join-customfunction.groovy[tag=code]
----
_Output_
....
╔═══════╤════════╤═══════╤═════╤══════════╗
║ name  │ sex    │ name  │ age │ hobby    ║
╠═══════╪════════╪═══════╪═════╪══════════╣
║ alex  │ male   │ alex  │ 21  │ biking   ║
╟───────┼────────┼───────┼─────┼──────────╢
║ sara  │ female │ sara  │ -   │ -        ║
╟───────┼────────┼───────┼─────┼──────────╢
║ peter │ -      │ peter │ 21  │ swimming ║
╚═══════╧════════╧═══════╧═════╧══════════╝

....


=== DATA QUERYING

==== Iterating over records

You can use any of the groovy methods to iterate of a `FuzzyCSVTable` since it implements Iterable.

[source,groovy]
----
include::samples/iterating.groovy[tag=code]
----
_Output_
....
alex
peter
....


==== Get Cell Value or First Value

[source,groovy]
----
include::samples/get-cell-value.groovy[tag=code]
----

==== Filter Records

[source,groovy]
----
include::samples/filters.groovy[tag=code]
----
_Output_
....
╔══════╤═════╤════════╗
║ name │ age │ hobby  ║
╠══════╪═════╪════════╣
║ alex │ 21  │ biking ║
╚══════╧═════╧════════╝

....


==== Sorting

[source,groovy]
----
include::samples/sorting.groovy[tag=code]
----
_Output_
....
---- SORTED WITH COLUMN NAMES
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ alex   │ 21  │ biking   ║
╟────────┼─────┼──────────╢
║ peter  │ 21  │ swimming ║
╟────────┼─────┼──────────╢
║ dan    │ 25  │ swimming ║
╟────────┼─────┼──────────╢
║ martin │ 40  │ swimming ║
╚════════╧═════╧══════════╝
 

---- SORTED WITH CLOSURE
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ alex   │ 21  │ biking   ║
╟────────┼─────┼──────────╢
║ peter  │ 21  │ swimming ║
╟────────┼─────┼──────────╢
║ dan    │ 25  │ swimming ║
╟────────┼─────┼──────────╢
║ martin │ 40  │ swimming ║
╚════════╧═════╧══════════╝
 

....


==== Ranges

Ranges help slice the table data. e.g. selecting last 2, top 2, 3rd to 2nd last record

[source,groovy]
----
include::samples/ranges.groovy[tag=code]
----
_Output_
....
---- TOP 2
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ alex   │ 21  │ biking   ║
╟────────┼─────┼──────────╢
║ martin │ 40  │ swimming ║
╚════════╧═════╧══════════╝
 

---- LAST 2
╔═══════╤═════╤══════════╗
║ name  │ age │ hobby    ║
╠═══════╪═════╪══════════╣
║ peter │ 21  │ swimming ║
╟───────┼─────┼──────────╢
║ dan   │ 25  │ swimming ║
╚═══════╧═════╧══════════╝


---- MIDDLE 2
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ martin │ 40  │ swimming ║
╟────────┼─────┼──────────╢
║ dan    │ 25  │ swimming ║
╚════════╧═════╧══════════╝
 

....



==== Record Navigation

Example showing running sum

[source,groovy]
----
include::samples/navigation-running-sum.groovy[tag=code]
----
_Output_
....
╔══════╤═════╤═════════════╗
║ name │ age │ running_sum ║
╠══════╪═════╪═════════════╣
║ kay  │ 1   │ 1           ║
╟──────┼─────┼─────────────╢
║ sa   │ 22  │ 23          ║
╟──────┼─────┼─────────────╢
║ kay2 │ 1   │ 24          ║
╟──────┼─────┼─────────────╢
║ ben  │ 10  │ 34          ║
╚══════╧═════╧═════════════╝

....


Or sum bottom value with current value

[source,groovy]
----
tbl(csv).addColumn(fx("bottom_up") { (it.down().age ?: 0) + it.age }).printTable()
----

==== Cell Navigation

Navigators help move through the table cells easily.You can look above,below, right or left of a cell.

[source,groovy]
----
include::samples/navigation.groovy[tag=code]
----

==== Select function

To shoe the difference of how `Record.fx` and `Record.fn`  observe the output of the following code snippet

[source,groovy]
----
include::samples/select-with-function.groovy[tag=code]
----
_Output_
....

--- USING FN FUNCTION
╔═══════╤══════════╤═══════╗
║ price │ quantity │ total ║
╠═══════╪══════════╪═══════╣
║ 2     │ 5        │ 10    ║
╟───────┼──────────┼───────╢
║ 3     │ 4        │ 12    ║
╚═══════╧══════════╧═══════╝


--- USING FX FUNTION
╔═══════╤══════════╤═══════╗
║ price │ quantity │ total ║
╠═══════╪══════════╪═══════╣
║ 2     │ 5        │ 22222 ║
╟───────┼──────────┼───────╢
║ 3     │ 4        │ 3333  ║
╚═══════╧══════════╧═══════╝



....




=== DATA MANIPULATION FUNCTIONS

==== Delete Records

[source,groovy]
----
include::samples/delete-rows.groovy[tag=code]
----
_Output_
....
╔═════════╤═════╤══════════╤══════════╗
║ name    │ age │ hobby    │ category ║
╠═════════╪═════╪══════════╪══════════╣
║ barbara │ 23  │ swimming │ S        ║
╚═════════╧═════╧══════════╧══════════╝

....


==== Deduplicate by column

[source,groovy]
----
include::samples/distinct-by-column.groovy[tag=code]
----
_Output_
....
╔═════════╤═════╤══════════╤══════════╗
║ name    │ age │ hobby    │ category ║
╠═════════╪═════╪══════════╪══════════╣
║ alex    │ 21  │ biking   │ A        ║
╟─────────┼─────┼──────────┼──────────╢
║ peter   │ 21  │ swimming │ S        ║
╟─────────┼─────┼──────────┼──────────╢
║ barbara │ 23  │ swimming │ S        ║
╚═════════╧═════╧══════════╧══════════╝

....


==== Adding Records

[source,groovy]
----
include::samples/adding-records.groovy[tag=code]
----
_Output_
....
╔══════════╤════════╗
║ name     │ number ║
╠══════════╪════════╣
║ join     │ 1.1    ║
╟──────────┼────────╢
║ JB       │ 455    ║
╟──────────┼────────╢
║ JLis     │ 767    ║
╟──────────┼────────╢
║ MName    │ 90     ║
╟──────────┼────────╢
║ -        │ -      ║
╟──────────┼────────╢
║ MNameEmp │ -      ║
╚══════════╧════════╝

....


==== Update values with where clause

[source,groovy]
----
include::samples/update-where.groovy[tag=code]
----
_Output_
....
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ alex   │ 900 │ running  ║
╟────────┼─────┼──────────╢
║ martin │ 40  │ swimming ║
╟────────┼─────┼──────────╢
║ dan    │ 900 │ running  ║
╟────────┼─────┼──────────╢
║ peter  │ 21  │ swimming ║
╚════════╧═════╧══════════╝

....


==== Transform each cell record

[source,groovy]
----
include::samples/transform-each.groovy[tag=code]
----
_Output_
....
╔════════════╤════════════╤════════════╗
║ name       │ age        │ hobby      ║
╠════════════╪════════════╪════════════╣
║ alex------ │ 21-------- │ biking---- ║
╟────────────┼────────────┼────────────╢
║ martin---- │ 40-------- │ swimming-- ║
╟────────────┼────────────┼────────────╢
║ dan------- │ 25-------- │ swimming-- ║
╟────────────┼────────────┼────────────╢
║ peter----- │ 21-------- │ swimming-- ║
╚════════════╧════════════╧════════════╝

....


=== DATA RESHAPING FUNCTIONS (COLUMN MANIPULATION)

==== Delete Column

[source,groovy]
----
include::samples/delete-column.groovy[tag=code]
----
_Output_
....
╔══════════╗
║ hobby    ║
╠══════════╣
║ biking   ║
╟──────────╢
║ swimming ║
╚══════════╝

....


==== Add Column

[source,groovy]
----
include::samples/add-column.groovy[tag=code]
----
_Output_
....
╔═══════╤═════╤══════════╤════════════╗
║ name  │ age │ hobby    │ Double Age ║
╠═══════╪═════╪══════════╪════════════╣
║ alex  │ 21  │ biking   │ 42         ║
╟───────┼─────┼──────────┼────────────╢
║ peter │ 13  │ swimming │ 26         ║
╚═══════╧═════╧══════════╧════════════╝

....


==== Transposing

[source,groovy]
----
include::samples/transpose.groovy[tag=code]
----
_Output_
....
╔═══════╤════════╤══════════╤══════════╤══════════╗
║ name  │ alex   │ martin   │ dan      │ peter    ║
╠═══════╪════════╪══════════╪══════════╪══════════╣
║ age   │ 21     │ 40       │ 25       │ 21       ║
╟───────┼────────┼──────────┼──────────┼──────────╢
║ hobby │ biking │ swimming │ swimming │ swimming ║
╚═══════╧════════╧══════════╧══════════╧══════════╝

....


==== Unwinding a column

This is kind can be used to unwind a column which has nested lists or collections

[source,groovy]
----
include::samples/unwind-list.groovy[tag=code]
----
_Output_
....
╔══════════╤═════════╗
║ name     │ AgeList ║
╠══════════╪═════════╣
║ biking   │ 21      ║
╟──────────┼─────────╢
║ biking   │ 16      ║
╟──────────┼─────────╢
║ swimming │ 21      ║
╟──────────┼─────────╢
║ swimming │ 15      ║
╚══════════╧═════════╝

....


==== Spreading a column

Expand outwards a column which contains list items

[source,groovy]
----
include::samples/spread-list.groovy[tag=code]
----
_Output_
....
╔══════════╤═══════════╤═══════════╗
║ name     │ AgeList_1 │ AgeList_2 ║
╠══════════╪═══════════╪═══════════╣
║ biking   │ 21        │ 16        ║
╟──────────┼───────────┼───────────╢
║ swimming │ 21        │ 15        ║
╚══════════╧═══════════╧═══════════╝

....


Spread out a column with maps

[source,groovy]
----
include::samples/spread-map.groovy[tag=code]
----
_Output_
....
╔══════════╤═════════╤════════════╗
║ name     │ Age_age │ Age_height ║
╠══════════╪═════════╪════════════╣
║ biking   │ 21      │ 16         ║
╟──────────┼─────────┼────────────╢
║ swimming │ 21      │ 15         ║
╚══════════╧═════════╧════════════╝

....


Spread with custom column names

[source,groovy]
----
include::samples/spread-map-custom.groovy[tag=code]
----
_Output_
....
╔══════════╤════════════════╤═══════════════════╗
║ name     │ MyColName: age │ MyColName: height ║
╠══════════╪════════════════╪═══════════════════╣
║ biking   │ 21             │ 16                ║
╟──────────┼────────────────┼───────────────────╢
║ swimming │ 21             │ 15                ║
╚══════════╧════════════════╧═══════════════════╝

....


==== Move column

[source,groovy]
----
include::samples/move-column.groovy[tag=code]
----
_Output_
....
╔═════════╤══════════╤══════════╤═════╗
║ name    │ hobby    │ category │ age ║
╠═════════╪══════════╪══════════╪═════╣
║ alex    │ biking   │ A        │ 21  ║
╟─────────┼──────────┼──────────┼─────╢
║ peter   │ swimming │ S        │ 21  ║
╟─────────┼──────────┼──────────┼─────╢
║ charles │ swimming │ S        │ 21  ║
╟─────────┼──────────┼──────────┼─────╢
║ barbara │ swimming │ S        │ 23  ║
╚═════════╧══════════╧══════════╧═════╝

....



=== AGGREGATION FUNCTIONS

==== Simplistic Aggregations

In the example below we find the average age in each hobby by making use of sum count and group by functions

[source,groovy]
----
include::samples/aggregation-simple.groovy[tag=code]
----
_Output_
....
╔══════════╤════════╤══════════╗
║ Hobby    │ TT.Age │ TT.Count ║
╠══════════╪════════╪══════════╣
║ biking   │ 37     │ 2        ║
╟──────────┼────────┼──────────╢
║ swimming │ 36     │ 2        ║
╚══════════╧════════╧══════════╝

....


==== Custom Aggregation

[source,groovy]
----
include::samples/aggregation-custom.groovy[tag=code]
----
_Output_
....
╔══════════╤══════════╗
║ Hobby    │ AgeList  ║
╠══════════╪══════════╣
║ biking   │ [21, 16] ║
╟──────────┼──────────╢
║ swimming │ [21, 15] ║
╚══════════╧══════════╝

....



=== EXPORT FUNCTIONS

==== CSV To MapList

[source,groovy]
----
include::samples/csv-to-map.groovy[tag=code]
----
_Output_
....
[[name:alex, age:21, hobby:biking], [name:peter, age:21, hobby:swimming]]
....


==== CSV To POJO List

[source,groovy]
----
include::samples/csv-to-pojo.groovy[]
----

==== Sql To CSV

[source,groovy]
----
groovy.sql.Sql groovySql = null//...
FuzzyCSVTable.toCSV(groovySql,"select * from PERSON")
----

OR

[source,groovy]
----
ResultSet resultSet = null//..
FuzzyCSVTable.toCSV(resultSet)
----

=== EXCEL UTILITY CLASSES

To use the Excel utilities you have to add the poi dependency to your classpath

If you are using gradle add this.

[source,groovy]
----
 compile 'org.apache.poi:poi-ooxml:3.16', {
     exclude group: 'stax', module: 'stax-api'
 }
 compile 'org.apache.poi:ooxml-schemas:1.3', {
     exclude group: 'stax', module: 'stax-api'
 }
----

After this you can use the Excel utilities to convert excel sheets to and from FuzzyCSVTables.

There are mainly two classes that help with this which include `fuzzycsv.Excel2Csv` and `fuzzycsv.CSVToExcel`

== Note:

This library has not been tested with very large(700,000 records plus) CSV files.So performance might be a concern.

More example can be seen here

https://github.com/kayr/fuzzy-csv/blob/master/src/test/groovy/fuzzycsv/FuzzyCSVTest.groovy

and

https://github.com/kayr/fuzzy-csv/blob/master/src/test/groovy/fuzzycsv/FuzzyCSVTableTest.groovy
