= Fuzzy-CSV
:toc: left
:source-highlighter: coderay
:toclevels: 4
FuzzyCSV is a lightweigt groovy data processing library that helps in shaping and cleaning your dataset before its consumed by another service.

== Get FuzzyCsv

FuzzyCsv is published to both maven central and jitpack.io.
Starting from 1.7.1 all versions of FuzzyCSV will be published to maven central

=== Get FuzzyCsv from Maven Central

For maven add the dependency to your pom file like this

Maven

[source,xml]
----
<dependency>
     <groupId>io.github.kayr</groupId>
     <artifactId>fuzzy-csv</artifactId>
     <version>${version}</version>
</dependency>
----

Gradle:

[source,groovy]
----
 compile 'io.github.kayr:fuzzy-csv:${version}'
----

=== Get FuzzyCsv from jitpack.io

The to get artefacts from jipack the name space changes from `io.github.kayr` to `com.github.kayr`.

For Maven

[source,xml]
-----

    ...
    <!-- Add this Repository -->
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    ...
    <dependency>
            <groupId>com.github.kayr</groupId>
            <artifactId>fuzzy-csv</artifactId>
            <version>${version}</version>
    </dependency>
    ...
-----

For Gradle

[source,groovy]
-----
repositories {
    /* Add this repository */
    maven { url 'https://jitpack.io' }
}

dependencies{
    ...
    compile 'com.github.kayr:fuzzy-csv:${version}'
    ...
}
-----

=== Illustrations

==== Loading Data into Fuzzy-CSV

[source,groovy]
----
include::samples/loading.groovy[tag=code]
----

==== Visualize json data in a console grid table

You can convert json text to a grid console table.

[source,groovy]
----
include::samples/gridify.groovy[tag=code]
/*output
╔═════════╤═══════════════════════════════════════════╗
║ key     │ value                                     ║
╠═════════╪═══════════════════════════════════════════╣
║ id      │ 0001                                      ║
╟─────────┼───────────────────────────────────────────╢
║ type    │ donut                                     ║
╟─────────┼───────────────────────────────────────────╢
║ name    │ Cake                                      ║
╟─────────┼───────────────────────────────────────────╢
║ ppu     │ 0.55                                      ║
╟─────────┼───────────────────────────────────────────╢
║ batters │ ╔════════╤══════════════════════════════╗ ║
║         │ ║ key    │ value                        ║ ║
║         │ ╠════════╪══════════════════════════════╣ ║
║         │ ║ batter │ ╔══════╤═══════════╤═══════╗ ║ ║
║         │ ║        │ ║ id   │ type      │ color ║ ║ ║
║         │ ║        │ ╠══════╪═══════════╪═══════╣ ║ ║
║         │ ║        │ ║ 1001 │ Regular   │ -     ║ ║ ║
║         │ ║        │ ╟──────┼───────────┼───────╢ ║ ║
║         │ ║        │ ║ 1002 │ Chocolate │ Brown ║ ║ ║
║         │ ║        │ ╚══════╧═══════════╧═══════╝ ║ ║
║         │ ╚════════╧══════════════════════════════╝ ║
╟─────────┼───────────────────────────────────────────╢
║ topping │ ╔══════╤════════╤═══════╗                 ║
║         │ ║ id   │ type   │ color ║                 ║
║         │ ╠══════╪════════╪═══════╣                 ║
║         │ ║ 5001 │ None   │ -     ║                 ║
║         │ ╟──────┼────────┼───────╢                 ║
║         │ ║ 5002 │ Glazed │ -     ║                 ║
║         │ ╟──────┼────────┼───────╢                 ║
║         │ ║ 5005 │ Sugar  │ Brown ║                 ║
║         │ ╚══════╧════════╧═══════╝                 ║
╚═════════╧═══════════════════════════════════════════╝
*/

----


==== Merging with a fuzzy match

1. Set the accuracy threshold to 75%
2. Merge using code below

[source,groovy]
----
include::samples/merging.groovy[tag=code]


//Notice how it merged [first name] and [ferts nama]
/*output
╔════════════╤════════╤═════╗
║ first name │ sex    │ age ║
╠════════════╪════════╪═════╣
║ alex       │ male   │ -   ║
╟────────────┼────────┼─────╢
║ sara       │ female │ -   ║
╟────────────┼────────┼─────╢
║ alex       │ male   │ 21  ║
╟────────────┼────────┼─────╢
║ peter      │ male   │ 21  ║
╚════════════╧════════╧═════╝
*/

----



Notice how it merged *_[first name]_* and *_[ferts nama]_*

=== Joins

==== Inner join

[source,groovy]
----
include::samples/join-inner.groovy[tag=code]

/*output
╔══════╤══════╤═════╤════════╗
║ name │ sex  │ age │ hobby  ║
╠══════╪══════╪═════╪════════╣
║ alex │ male │ 21  │ biking ║
╚══════╧══════╧═════╧════════╝
*/

----


==== Left Join

[source,groovy]
----
include::samples/join-left.groovy[tag=code]

/*output
╔══════╤════════╤═════╤════════╗
║ name │ sex    │ age │ hobby  ║
╠══════╪════════╪═════╪════════╣
║ alex │ male   │ 21  │ biking ║
╟──────┼────────┼─────┼────────╢
║ sara │ female │ -   │ -      ║
╚══════╧════════╧═════╧════════╝
*/

----


==== Right Join

[source,groovy]
----
include::samples/join-right.groovy[tag=code]

/*output
╔═══════╤══════╤═════╤══════════╗
║ name  │ sex  │ age │ hobby    ║
╠═══════╪══════╪═════╪══════════╣
║ alex  │ male │ 21  │ biking   ║
╟───────┼──────┼─────┼──────────╢
║ peter │ -    │ 21  │ swimming ║
╚═══════╧══════╧═════╧══════════╝
*/

----


==== Full Join

[source,groovy]
----
include::samples/join-full.groovy[tag=code]

/*output
╔═══════╤════════╤═════╤══════════╗
║ name  │ sex    │ age │ hobby    ║
╠═══════╪════════╪═════╪══════════╣
║ alex  │ male   │ 21  │ biking   ║
╟───────┼────────┼─────┼──────────╢
║ sara  │ female │ -   │ -        ║
╟───────┼────────┼─────┼──────────╢
║ peter │ -      │ 21  │ swimming ║
╚═══════╧════════╧═════╧══════════╝
*/

----
==== Join With Custom Function

[source,groovy]
----
include::samples/join-customfunction.groovy[tag=code]

/*output
╔═══════╤════════╤═══════╤═════╤══════════╗
║ name  │ sex    │ name  │ age │ hobby    ║
╠═══════╪════════╪═══════╪═════╪══════════╣
║ alex  │ male   │ alex  │ 21  │ biking   ║
╟───────┼────────┼───────┼─────┼──────────╢
║ sara  │ female │ sara  │ -   │ -        ║
╟───────┼────────┼───────┼─────┼──────────╢
║ peter │ -      │ peter │ 21  │ swimming ║
╚═══════╧════════╧═══════╧═════╧══════════╝
*/

----

=== Record Functions

These Help you write expression or functions for a record.E.g A function multiplying price by quantity.The record function run in two modes:

- One with type coercion which can be created using `RecordFx.fn{}`.This mode is lenient and does not throw most exceptions.This mode supports division of nulls(`null/2`), zero(`2/0`) division and type coercion(`"2"/2 or Object/null`) . This mode adds extra overhead and is much slower if your are dealing with lots of records.
- Another mode is `RecordFx.fx{}` which uses the default groovy evaluator.This mode is much faster if you are working with lots of records.However, this mode is not lenient and hence can throw `java.lang.ArithmeticException: Division by zero`.If you want to enable leniency but still want to use the faster `RecordFx.fx{}` you can wrap your code in the `fuzzycsv.FxExtensions` category(e.g `use(FxExtensions){ ...code here.. }`) So the category is registered only once as compared to the former where the category is reqistered on each and every evaluation.


==== Doing a Select with a calculated field

To shoe the difference of how `Record.fx` and `Record.fn`  observe the output of the following code snippet

[source,groovy]
----
include::samples/select-with-function.groovy[tag=code]

/*output

--- USING FN FUNCTION
╔═══════╤══════════╤═══════╗
║ price │ quantity │ total ║
╠═══════╪══════════╪═══════╣
║ 2     │ 5        │ 10    ║
╟───────┼──────────┼───────╢
║ 3     │ 4        │ 12    ║
╚═══════╧══════════╧═══════╝


--- USING FX FUNTION
╔═══════╤══════════╤═══════╗
║ price │ quantity │ total ║
╠═══════╪══════════╪═══════╣
║ 2     │ 5        │ 22222 ║
╟───────┼──────────┼───────╢
║ 3     │ 4        │ 3333  ║
╚═══════╧══════════╧═══════╝


*/

----

=== Data Manipulation Functions

==== Iterating over records

You can use any of the groovy methods to iterate of a `FuzzyCSVTable` since it implements Iterable.

[source,groovy]
-----
include::samples/iterating.groovy[tag=code]
/*output
alex
peter*/

-----

==== Get Cell Value or First Value

[source,groovy]
----
include::samples/get-cell-value.groovy[]
----

==== Delete Column

[source,groovy]
----
include::samples/delete-column.groovy[]

/*output
╔══════════╗
║ hobby    ║
╠══════════╣
║ biking   ║
╟──────────╢
║ swimming ║
╚══════════╝
*/

----

==== CSV To MapList

[source,groovy]
----
include::samples/csv-to-map.groovy[]

/*output
[[name:alex, age:21, hobby:biking], [name:peter, age:21, hobby:swimming]]*/

----

==== CSV To POJO List

[source,groovy]
----
include::samples/csv-to-pojo.groovy[]
----

==== Sql To CSV

[source,groovy]
----
import java.sql.ResultSet
import groovy.sql.Sql
import fuzzycsv.FuzzyCSVTable

Sql groovySql = null//...
FuzzyCSVTable.toCSV(groovySql,"select * from PERSON")
//or
ResultSet resultSet = null//..
FuzzyCSVTable.toCSV(resultSet)
----

==== Add Column
[source,groovy]
----
include::samples/add-column.groovy[]
/*output
╔═══════╤═════╤══════════╤════════════╗
║ name  │ age │ hobby    │ Double Age ║
╠═══════╪═════╪══════════╪════════════╣
║ alex  │ 21  │ biking   │ 42         ║
╟───────┼─────┼──────────┼────────────╢
║ peter │ 13  │ swimming │ 26         ║
╚═══════╧═════╧══════════╧════════════╝
*/

----

==== Filter Records
[source,groovy]
----
include::samples/filters.groovy[]
/*output
╔══════╤═════╤════════╗
║ name │ age │ hobby  ║
╠══════╪═════╪════════╣
║ alex │ 21  │ biking ║
╚══════╧═════╧════════╝
*/

----

==== Delete Records

[source,groovy]
----
include::samples/delete-rows.groovy[]
/*output
╔═════════╤═════╤══════════╤══════════╗
║ name    │ age │ hobby    │ category ║
╠═════════╪═════╪══════════╪══════════╣
║ barbara │ 23  │ swimming │ S        ║
╚═════════╧═════╧══════════╧══════════╝
*/

----

==== Distinct by column

[source,groovy]
----
include::samples/distinct-by-column.groovy[]
/*output
╔═════════╤═════╤══════════╤══════════╗
║ name    │ age │ hobby    │ category ║
╠═════════╪═════╪══════════╪══════════╣
║ alex    │ 21  │ biking   │ A        ║
╟─────────┼─────┼──────────┼──────────╢
║ peter   │ 21  │ swimming │ S        ║
╟─────────┼─────┼──────────┼──────────╢
║ barbara │ 23  │ swimming │ S        ║
╚═════════╧═════╧══════════╧══════════╝
*/

----

==== Adding Records

[source,groovy]
----
include::samples/adding-records.groovy[]
/*output
╔══════════╤════════╗
║ name     │ number ║
╠══════════╪════════╣
║ john     │ 1.1    ║
╟──────────┼────────╢
║ JB       │ 455    ║
╟──────────┼────────╢
║ JLis     │ 767    ║
╟──────────┼────────╢
║ MName    │ 90     ║
╟──────────┼────────╢
║ -        │ -      ║
╟──────────┼────────╢
║ MNameEmp │ -      ║
╚══════════╧════════╝
*/

----

==== Sorting

[source,groovy]
----
include::samples/sorting.groovy[tag=code]
/*output
---- SORTED WITH COLUMN NAMES
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ alex   │ 21  │ biking   ║
╟────────┼─────┼──────────╢
║ peter  │ 21  │ swimming ║
╟────────┼─────┼──────────╢
║ dan    │ 25  │ swimming ║
╟────────┼─────┼──────────╢
║ martin │ 40  │ swimming ║
╚════════╧═════╧══════════╝
 

---- SORTED WITH CLOSURE
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ alex   │ 21  │ biking   ║
╟────────┼─────┼──────────╢
║ peter  │ 21  │ swimming ║
╟────────┼─────┼──────────╢
║ dan    │ 25  │ swimming ║
╟────────┼─────┼──────────╢
║ martin │ 40  │ swimming ║
╚════════╧═════╧══════════╝
 
*/

----
==== Ranges
Ranges help slice the table data. e.g. selecting last 2, top 2,  3rd to 2nd last record

[source,groovy]
----
include::samples/ranges.groovy[tag=code]
/*output
---- TOP 2
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ alex   │ 21  │ biking   ║
╟────────┼─────┼──────────╢
║ martin │ 40  │ swimming ║
╚════════╧═════╧══════════╝
 

---- LAST 2
╔═══════╤═════╤══════════╗
║ name  │ age │ hobby    ║
╠═══════╪═════╪══════════╣
║ peter │ 21  │ swimming ║
╟───────┼─────┼──────────╢
║ dan   │ 25  │ swimming ║
╚═══════╧═════╧══════════╝


---- MIDDLE 2
╔════════╤═════╤══════════╗
║ name   │ age │ hobby    ║
╠════════╪═════╪══════════╣
║ martin │ 40  │ swimming ║
╟────────┼─────┼──────────╢
║ dan    │ 25  │ swimming ║
╚════════╧═════╧══════════╝
 
*/

----

=== Navigation

To be continued..